// A starting shelf of well-known Tamil soundtracks.
//
// These are commercial releases, so the audio isn't free anywhere — the app
// can't host them. What it can do is take you straight to them on YouTube,
// where the labels publish officially and get paid per play.
//
// Add your own rows freely: { title, year, music, actor }.

export const FILMS = [
  // 1980s
  { title: "Moondram Pirai", year: 1982, music: "Ilaiyaraaja", actor: "Kamal Haasan" },
  { title: "Mouna Ragam", year: 1986, music: "Ilaiyaraaja", actor: "Revathi" },
  { title: "Punnagai Mannan", year: 1986, music: "Ilaiyaraaja", actor: "Kamal Haasan" },
  { title: "Nayakan", year: 1987, music: "Ilaiyaraaja", actor: "Kamal Haasan" },
  { title: "Agni Natchathiram", year: 1988, music: "Ilaiyaraaja", actor: "Prabhu" },
  { title: "Apoorva Sagodharargal", year: 1989, music: "Ilaiyaraaja", actor: "Kamal Haasan" },

  // 1990s
  { title: "Anjali", year: 1990, music: "Ilaiyaraaja", actor: "Raghuvaran" },
  { title: "Michael Madana Kama Rajan", year: 1990, music: "Ilaiyaraaja", actor: "Kamal Haasan" },
  { title: "Guna", year: 1991, music: "Ilaiyaraaja", actor: "Kamal Haasan" },
  { title: "Chinna Thambi", year: 1991, music: "Ilaiyaraaja", actor: "Prabhu" },
  { title: "Thalapathi", year: 1991, music: "Ilaiyaraaja", actor: "Rajinikanth" },
  { title: "Roja", year: 1992, music: "A.R. Rahman", actor: "Madhavan" },
  { title: "Gentleman", year: 1993, music: "A.R. Rahman", actor: "Arjun" },
  { title: "Thiruda Thiruda", year: 1993, music: "A.R. Rahman", actor: "Prashanth" },
  { title: "Kadhalan", year: 1994, music: "A.R. Rahman", actor: "Prabhu Deva" },
  { title: "Duet", year: 1994, music: "A.R. Rahman", actor: "Prabhu" },
  { title: "Karuththamma", year: 1994, music: "A.R. Rahman", actor: "Raja" },
  { title: "Baasha", year: 1995, music: "Deva", actor: "Rajinikanth" },
  { title: "Bombay", year: 1995, music: "A.R. Rahman", actor: "Arvind Swamy" },
  { title: "Aasai", year: 1995, music: "Deva", actor: "Ajith Kumar" },
  { title: "Indian", year: 1996, music: "A.R. Rahman", actor: "Kamal Haasan" },
  { title: "Kadhal Desam", year: 1996, music: "A.R. Rahman", actor: "Abbas" },
  { title: "Kaadhal Kottai", year: 1996, music: "Deva", actor: "Ajith Kumar" },
  { title: "Minsara Kanavu", year: 1997, music: "A.R. Rahman", actor: "Prabhu Deva" },
  { title: "Iruvar", year: 1997, music: "A.R. Rahman", actor: "Mohanlal" },
  { title: "Kadhalukku Mariyadhai", year: 1997, music: "Ilaiyaraaja", actor: "Vijay" },
  { title: "Nerrukku Ner", year: 1997, music: "Deva", actor: "Suriya" },
  { title: "Jeans", year: 1998, music: "A.R. Rahman", actor: "Prashanth" },
  { title: "Kadhal Mannan", year: 1998, music: "Bharadwaj", actor: "Ajith Kumar" },
  { title: "Sethu", year: 1999, music: "Ilaiyaraaja", actor: "Vikram" },
  { title: "Vaalee", year: 1999, music: "Deva", actor: "Ajith Kumar" },
  { title: "Padayappa", year: 1999, music: "A.R. Rahman", actor: "Rajinikanth" },
  { title: "Mudhalvan", year: 1999, music: "A.R. Rahman", actor: "Arjun" },
  { title: "Kaadhalar Dhinam", year: 1999, music: "A.R. Rahman", actor: "Kunal" },
  { title: "Amarkalam", year: 1999, music: "Bharadwaj", actor: "Ajith Kumar" },
  { title: "En Swasa Kaatre", year: 1999, music: "A.R. Rahman", actor: "Arvind Swamy" },

  // 2000s
  { title: "Alaipayuthey", year: 2000, music: "A.R. Rahman", actor: "Madhavan" },
  { title: "Kandukondain Kandukondain", year: 2000, music: "A.R. Rahman", actor: "Madhavan" },
  { title: "Mugavaree", year: 2000, music: "Deva", actor: "Ajith Kumar" },
  { title: "Minnale", year: 2001, music: "Harris Jayaraj", actor: "Madhavan" },
  { title: "Star", year: 2001, music: "A.R. Rahman", actor: "Prashanth" },
  { title: "Dumm Dumm Dumm", year: 2001, music: "Karthik Raja", actor: "Madhavan" },
  { title: "Friends", year: 2001, music: "Ilaiyaraaja", actor: "Vijay" },
  { title: "Majunu", year: 2001, music: "Harris Jayaraj", actor: "Prashanth" },
  { title: "12B", year: 2001, music: "Harris Jayaraj", actor: "Shaam" },
  { title: "Kannathil Muthamittal", year: 2002, music: "A.R. Rahman", actor: "Madhavan" },
  { title: "Youth", year: 2002, music: "Mani Sharma", actor: "Vijay" },
  { title: "Kaakha Kaakha", year: 2003, music: "Harris Jayaraj", actor: "Suriya" },
  { title: "Kaadhal Kondein", year: 2003, music: "Yuvan Shankar Raja", actor: "Dhanush" },
  { title: "Pithamagan", year: 2003, music: "Ilaiyaraaja", actor: "Vikram" },
  { title: "Boys", year: 2003, music: "A.R. Rahman", actor: "Siddharth" },
  { title: "Saamy", year: 2003, music: "Harris Jayaraj", actor: "Vikram" },
  { title: "Ghilli", year: 2004, music: "Vidyasagar", actor: "Vijay" },
  { title: "Manmadhan", year: 2004, music: "Yuvan Shankar Raja", actor: "Silambarasan" },
  { title: "7G Rainbow Colony", year: 2004, music: "Yuvan Shankar Raja", actor: "Ravi Krishna" },
  { title: "Autograph", year: 2004, music: "Bharadwaj", actor: "Cheran" },
  { title: "Kaadhal", year: 2004, music: "Joshua Sridhar", actor: "Bharath" },
  { title: "Aayutha Ezhuthu", year: 2004, music: "A.R. Rahman", actor: "Suriya" },
  { title: "Virumaandi", year: 2004, music: "Ilaiyaraaja", actor: "Kamal Haasan" },
  { title: "Anniyan", year: 2005, music: "Harris Jayaraj", actor: "Vikram" },
  { title: "Ghajini", year: 2005, music: "Harris Jayaraj", actor: "Suriya" },
  { title: "Chandramukhi", year: 2005, music: "Vidyasagar", actor: "Rajinikanth" },
  { title: "Sachein", year: 2005, music: "Devi Sri Prasad", actor: "Vijay" },
  { title: "Sandakozhi", year: 2005, music: "Yuvan Shankar Raja", actor: "Vishal" },
  { title: "Vallavan", year: 2006, music: "Yuvan Shankar Raja", actor: "Silambarasan" },
  { title: "Pudhupettai", year: 2006, music: "Yuvan Shankar Raja", actor: "Dhanush" },
  { title: "Sillunu Oru Kaadhal", year: 2006, music: "A.R. Rahman", actor: "Suriya" },
  { title: "Vettaiyaadu Vilaiyaadu", year: 2006, music: "Harris Jayaraj", actor: "Kamal Haasan" },
  { title: "Mozhi", year: 2007, music: "Vidyasagar", actor: "Jyothika" },
  { title: "Billa", year: 2007, music: "Yuvan Shankar Raja", actor: "Ajith Kumar" },
  { title: "Polladhavan", year: 2007, music: "G.V. Prakash Kumar", actor: "Dhanush" },
  { title: "Paruthiveeran", year: 2007, music: "Yuvan Shankar Raja", actor: "Karthi" },
  { title: "Pokkiri", year: 2007, music: "Mani Sharma", actor: "Vijay" },
  { title: "Sivaji", year: 2007, music: "A.R. Rahman", actor: "Rajinikanth" },
  { title: "Subramaniapuram", year: 2008, music: "James Vasanthan", actor: "Jai" },
  { title: "Vaaranam Aayiram", year: 2008, music: "Harris Jayaraj", actor: "Suriya" },
  { title: "Saroja", year: 2008, music: "Yuvan Shankar Raja", actor: "Shiva" },
  { title: "Abhiyum Naanum", year: 2008, music: "Vidyasagar", actor: "Prakash Raj" },
  { title: "Ayan", year: 2009, music: "Harris Jayaraj", actor: "Suriya" },
  { title: "Naan Kadavul", year: 2009, music: "Ilaiyaraaja", actor: "Arya" },
  { title: "Vaamanan", year: 2009, music: "Yuvan Shankar Raja", actor: "Jai" },
  { title: "Dheena", year: 2001, music: "Yuvan Shankar Raja", actor: "Ajith Kumar" },
  { title: "Citizen", year: 2001, music: "Deva", actor: "Ajith Kumar" },
  { title: "Poovellam Un Vasam", year: 2001, music: "Yuvan Shankar Raja", actor: "Ajith Kumar" },
  { title: "Red", year: 2002, music: "Deva", actor: "Ajith Kumar" },
  { title: "Villain", year: 2002, music: "Bharadwaj", actor: "Ajith Kumar" },
  { title: "Kadhal Azhivathillai", year: 2002, music: "Bharadwaj", actor: "Silambarasan" },
  { title: "Anjaneya", year: 2003, music: "Mani Sharma", actor: "Ajith Kumar" },
  { title: "Kuthu", year: 2004, music: "Srikanth Deva", actor: "Silambarasan" },
  { title: "Ji", year: 2005, music: "Vidyasagar", actor: "Ajith Kumar" },
  { title: "Paramasivan", year: 2006, music: "Vidyasagar", actor: "Ajith Kumar" },
  { title: "Saravana", year: 2006, music: "Srikanth Deva", actor: "Silambarasan" },
  { title: "Aalwar", year: 2007, music: "Srikanth Deva", actor: "Ajith Kumar" },
  { title: "Kireedam", year: 2007, music: "G.V. Prakash Kumar", actor: "Ajith Kumar" },
  { title: "Aegan", year: 2008, music: "Yuvan Shankar Raja", actor: "Ajith Kumar" },
  { title: "Silambattam", year: 2008, music: "Yuvan Shankar Raja", actor: "Silambarasan" },
  { title: "Kaalai", year: 2008, music: "Yuvan Shankar Raja", actor: "Silambarasan" },

  // 2010s
  { title: "Vinnaithaandi Varuvaayaa", year: 2010, music: "A.R. Rahman", actor: "Silambarasan" },
  { title: "Enthiran", year: 2010, music: "A.R. Rahman", actor: "Rajinikanth" },
  { title: "Paiyaa", year: 2010, music: "Yuvan Shankar Raja", actor: "Karthi" },
  { title: "Singam", year: 2010, music: "Devi Sri Prasad", actor: "Suriya" },
  { title: "Boss Engira Bhaskaran", year: 2010, music: "Yuvan Shankar Raja", actor: "Arya" },
  { title: "Angadi Theru", year: 2010, music: "Vijay Antony", actor: "Mahesh" },
  { title: "Mynaa", year: 2010, music: "D. Imman", actor: "Vidharth" },
  { title: "Ko", year: 2011, music: "Harris Jayaraj", actor: "Jiiva" },
  { title: "Mankatha", year: 2011, music: "Yuvan Shankar Raja", actor: "Ajith Kumar" },
  { title: "Aadukalam", year: 2011, music: "G.V. Prakash Kumar", actor: "Dhanush" },
  { title: "Mayakkam Enna", year: 2011, music: "G.V. Prakash Kumar", actor: "Dhanush" },
  { title: "Deiva Thirumagal", year: 2011, music: "G.V. Prakash Kumar", actor: "Vikram" },
  { title: "7aum Arivu", year: 2011, music: "Harris Jayaraj", actor: "Suriya" },
  { title: "Vaagai Sooda Vaa", year: 2011, music: "Ghibran", actor: "Vimal" },
  { title: "3", year: 2012, music: "Anirudh Ravichander", actor: "Dhanush" },
  { title: "Thuppakki", year: 2012, music: "Harris Jayaraj", actor: "Vijay" },
  { title: "Kumki", year: 2012, music: "D. Imman", actor: "Vikram Prabhu" },
  { title: "Pizza", year: 2012, music: "Santhosh Narayanan", actor: "Vijay Sethupathi" },
  { title: "Neethane En Ponvasantham", year: 2012, music: "Ilaiyaraaja", actor: "Jiiva" },
  { title: "Nanban", year: 2012, music: "Harris Jayaraj", actor: "Vijay" },
  { title: "Attakathi", year: 2012, music: "Santhosh Narayanan", actor: "Dinesh" },
  { title: "Raja Rani", year: 2013, music: "G.V. Prakash Kumar", actor: "Arya" },
  { title: "Soodhu Kavvum", year: 2013, music: "Santhosh Narayanan", actor: "Vijay Sethupathi" },
  { title: "Maryan", year: 2013, music: "A.R. Rahman", actor: "Dhanush" },
  { title: "Kadal", year: 2013, music: "A.R. Rahman", actor: "Gautham Karthik" },
  { title: "Ethir Neechal", year: 2013, music: "Anirudh Ravichander", actor: "Sivakarthikeyan" },
  { title: "Vanakkam Chennai", year: 2013, music: "Anirudh Ravichander", actor: "Shiva" },
  { title: "Paradesi", year: 2013, music: "G.V. Prakash Kumar", actor: "Atharvaa" },
  { title: "Kaththi", year: 2014, music: "Anirudh Ravichander", actor: "Vijay" },
  { title: "Velaiilla Pattadhari", year: 2014, music: "Anirudh Ravichander", actor: "Dhanush" },
  { title: "Jigarthanda", year: 2014, music: "Santhosh Narayanan", actor: "Siddharth" },
  { title: "Madras", year: 2014, music: "Santhosh Narayanan", actor: "Karthi" },
  { title: "Anegan", year: 2015, music: "Harris Jayaraj", actor: "Dhanush" },
  { title: "I", year: 2015, music: "A.R. Rahman", actor: "Vikram" },
  { title: "Thani Oruvan", year: 2015, music: "Hiphop Tamizha", actor: "Jayam Ravi" },
  { title: "Kabali", year: 2016, music: "Santhosh Narayanan", actor: "Rajinikanth" },
  { title: "Theri", year: 2016, music: "G.V. Prakash Kumar", actor: "Vijay" },
  { title: "24", year: 2016, music: "A.R. Rahman", actor: "Suriya" },
  { title: "Remo", year: 2016, music: "Anirudh Ravichander", actor: "Sivakarthikeyan" },
  { title: "Mersal", year: 2017, music: "A.R. Rahman", actor: "Vijay" },
  { title: "Vikram Vedha", year: 2017, music: "Sam C.S.", actor: "Vijay Sethupathi" },
  { title: "Kaala", year: 2018, music: "Santhosh Narayanan", actor: "Rajinikanth" },
  { title: "96", year: 2018, music: "Govind Vasantha", actor: "Vijay Sethupathi" },
  { title: "Vada Chennai", year: 2018, music: "Santhosh Narayanan", actor: "Dhanush" },
  { title: "Petta", year: 2019, music: "Anirudh Ravichander", actor: "Rajinikanth" },
  { title: "Asuran", year: 2019, music: "G.V. Prakash Kumar", actor: "Dhanush" },
  { title: "Asal", year: 2010, music: "Bharadwaj", actor: "Ajith Kumar" },
  { title: "Vaanam", year: 2011, music: "Yuvan Shankar Raja", actor: "Silambarasan" },
  { title: "Osthe", year: 2011, music: "Thaman S", actor: "Silambarasan" },
  { title: "Billa II", year: 2012, music: "Yuvan Shankar Raja", actor: "Ajith Kumar" },
  { title: "Podaa Podi", year: 2012, music: "Dharan Kumar", actor: "Silambarasan" },
  { title: "Arrambam", year: 2013, music: "Yuvan Shankar Raja", actor: "Ajith Kumar" },
  { title: "Veeram", year: 2014, music: "Devi Sri Prasad", actor: "Ajith Kumar" },
  { title: "Yennai Arindhaal", year: 2015, music: "Harris Jayaraj", actor: "Ajith Kumar" },
  { title: "Vedalam", year: 2015, music: "Anirudh Ravichander", actor: "Ajith Kumar" },
  { title: "Vaalu", year: 2015, music: "Thaman S", actor: "Silambarasan" },
  { title: "Idhu Namma Aalu", year: 2016, music: "Thaman S", actor: "Silambarasan" },
  { title: "Achcham Yenbadhu Madamaiyada", year: 2016, music: "A.R. Rahman", actor: "Silambarasan" },
  { title: "Vivegam", year: 2017, music: "Anirudh Ravichander", actor: "Ajith Kumar" },
  { title: "Chekka Chivantha Vaanam", year: 2018, music: "A.R. Rahman", actor: "Silambarasan" },
  { title: "Viswasam", year: 2019, music: "D. Imman", actor: "Ajith Kumar" },
  { title: "Nerkonda Paarvai", year: 2019, music: "Yuvan Shankar Raja", actor: "Ajith Kumar" },
  { title: "Vantha Rajavathaan Varuven", year: 2019, music: "Hiphop Tamizha", actor: "Silambarasan" },

  // 2020s
  { title: "Master", year: 2021, music: "Anirudh Ravichander", actor: "Vijay" },
  { title: "Karnan", year: 2021, music: "Santhosh Narayanan", actor: "Dhanush" },
  { title: "Vikram", year: 2022, music: "Anirudh Ravichander", actor: "Kamal Haasan" },
  { title: "Ponniyin Selvan: I", year: 2022, music: "A.R. Rahman", actor: "Vikram" },
  { title: "Jailer", year: 2023, music: "Anirudh Ravichander", actor: "Rajinikanth" },
  { title: "Leo", year: 2023, music: "Anirudh Ravichander", actor: "Vijay" },
  { title: "Eeswaran", year: 2021, music: "Thaman S", actor: "Silambarasan" },
  { title: "Maanaadu", year: 2021, music: "Yuvan Shankar Raja", actor: "Silambarasan" },
  { title: "Valimai", year: 2022, music: "Yuvan Shankar Raja", actor: "Ajith Kumar" },
  { title: "Thunivu", year: 2023, music: "Ghibran", actor: "Ajith Kumar" },
  { title: "Pathu Thala", year: 2023, music: "A.R. Rahman", actor: "Silambarasan" },
];

export const DECADES = ["1980s", "1990s", "2000s", "2010s", "2020s"];

export const decadeOf = (year) => `${Math.floor(year / 10) * 10}s`;

export function filmsBy({ decade = "", music = "", actor = "" } = {}) {
  return FILMS.filter((f) =>
    (!decade || decadeOf(f.year) === decade) &&
    (!music || f.music === music) &&
    (!actor || f.actor === actor)
  ).sort((a, b) => a.year - b.year);
}

/** What to type into YouTube to get the soundtrack rather than the film. */
export const soundtrackQuery = (film) => `${film.title} ${film.year} full songs jukebox`;

// Buying is the only way to own commercial film music. These open a store search
// rather than a product page, since catalogue ids change and albums get reissued.
export const STORES = [
  {
    name: "Apple Music",
    url: (f) => `https://music.apple.com/in/search?term=${encodeURIComponent(`${f.title} ${f.music}`)}`,
  },
  {
    name: "Amazon",
    url: (f) => `https://www.amazon.in/s?k=${encodeURIComponent(`${f.title} tamil soundtrack cd`)}`,
  },
];
